version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: water_me_frontend
    environment:
      - NODE_ENV=docker
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - water_me_app
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    depends_on:
      - node-server

  node-server:
    build:
      context: ./backend
    container_name: water_me_backend
    environment:
      - NODE_ENV=docker
    ports:
      - '5000:5000'
    networks:
      - water_me_app
    volumes:
      - ./backend:/backend
      - node_modules:/backend/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=waterme_Docker
      - MYSQL_USER=DockerUser
      - MYSQL_PASSWORD=DockerUserTestpassword
      - MYSQL_ROOT_PASSWORD=DockerUserTestpassword
    ports:
      - '3306:3306'
    networks:
      - water_me_app
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  water_me_app:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  node_modules:
