version: '3.7'
networks:
  docker:

volumes:
  jenkins-data:
  jenkins-docker-certs:

services:
  jenkins:
    image: jenkinsci/blueocean
    restart: always
    networks:
      - docker
    ports:
      - 8080:8080
      - 50000:50000
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - ../water_me:/var/project/water_me
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    container_name: jenkins

  dind:
    image: docker:dind
    privileged: true
    restart: always
    networks:
      docker:
        aliases:
          - docker
    ports:
      - 2376:2376
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
      - ../water_me:/var/project/water_me
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    container_name: jenkins_dind
