version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: water_me_frontend
    environment:
      - NODE_ENV=docker
      - CHOKIDAR_USEPOLLING=true
    restart: always
    ports:
      - '3000:3000'
    networks:
      - water_me_app
    volumes:
      - ./frontend/:/water_me_frontend
      - node_modules_frontend:/water_me_frontend/node_modules
    stdin_open: true
    depends_on:
      - node-server

  node-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: water_me_backend
    restart: always
    environment:
      - NODE_ENV=docker
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:8080'
    networks:
      - water_me_app
    volumes:
      - ./backend/:/water_me_backend
      - node_modules_backend:/water_me_backend/node_modules
    stdin_open: true
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=waterme_Docker
      - MYSQL_USER=DockerUser
      - MYSQL_PASSWORD=DockerUserTestpassword
      - MYSQL_ROOT_PASSWORD=DockerUserTestpassword
    ports:
      - '3306:3306'
    networks:
      - water_me_app
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  water_me_app:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  node_modules_frontend:
    driver: local
  node_modules_backend:
    driver: local
